### ISSUE TITLE
Mardown Viewer ContentHeight always returns 24

### ISSUE THREAD

**Issue by nelson-yan** [megel/PCF-MarkDownViewer#26]
Mardown Viewer ContentHeight always returns 24

**Comment by megel** [comment]
Hi @nelson-yan yes, I can confirm when I output ContentHeight it shows in my gallery also 24. But did you also change the `Overflow` to `none`?

However, my **MarkDown Control** is automatically resized with this PowerFx formula:

```
Overflow := "none"
```

```
Height := Self.ContentHeight
```

**Comment by megel** [comment]
Closed // no feedback received
