### ISSUE TITLE
Capability with Model-Driven-Apps?

### ISSUE THREAD

**Issue by ralphwest1** [megel/PCF-MarkDownViewer#4]
@megel 
This is just the control I was looking for so thanks for sharing! 
I see that this control was built for canvas apps, my use case is to use in a Model-Driven-App.
Is this control compatible for model driven apps or could it be with a little tweaking?

**Comment by megel** [comment]
Thanks. 
Well, I have never tried to run it with Model-Driven-Apps but it should work too.
